### ISSUE TITLE
Pre-packaged efxclipse SDK 4.6.0 locks up when creating second JavaFX Project (Building workspace 19%)

### ISSUE THREAD

**Issue by tomsontom** [eclipse-efx/efxclipse-eclipse#15]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=518159

**Comment by matteg** [comment]
Yes I can reproduce the problem by starting a new JavaFx project whose name is the same as a JavaFX control such as TableView, ListView, etc.

As soon as I used a different project name (TabView) the project created successfully.

**Comment by wodinga** [comment]
Hey guys, is there a workaround for this yet? Or should I just manually create a JavaFX project?

**Comment by tomsontom** [comment]
Can one of you create a thread dump when this happens?

**Comment by wodinga** [comment]
How? I’m on MacOS

**Comment by tomsontom** [comment]
I assume this is fixed with #19
