### ISSUE TITLE
E(fx)clipse tooling install breaks ide theme compliance

### ISSUE THREAD

**Issue by MarceloRuiz** [eclipse-efx/efxclipse-eclipse#28]
Starting with the following system:

Eclipse for RCP and RAP Developers
Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200
OS: Linux, v.4.13.0-16-generic, x86_64 / gtk 3.22.24

After installing E(fx)clipse (latest version or nightly), the theme compliance gets broken. When using a dark theme, the result makes the IDE look strange in many sections.
Uninstalling E(fx)clipse leaves the IDE in a weird state regarding the theme compliance. Some parts get back to working, where others remain corrupted (even after restarting).
Enabling Theming and selecting a Dark theme is a partial workaround to the problem, because the IDE somehow blends its own dark theme with the system one, resulting in poor contrast in different parts.
Attached are pictures of the before and after the install

![jfx - eclipse _036](https://user-images.githubusercontent.com/1209270/32420272-7da621fa-c255-11e7-8f23-ec0c3635736f.jpg)
![jfx - eclipse _037](https://user-images.githubusercontent.com/1209270/32420273-81c7fe5c-c255-11e7-9251-6c9ca55f59ff.jpg)

**Comment by tomsontom** [comment]
As we don't contribute ANYTHING to themes I doubt we are the reason for the breakage
