### ISSUE TITLE
Generated exe file is not rendering fxml in loaded in "Part" class

### ISSUE THREAD

**Issue by leeroles** [eclipse-efx/efxclipse-eclipse#38]
Im trying to create a simple efxclipse rcp (e4) application using efxclipse 3.0.0 target runtime

The project structure are as follows
application.client.app
application.client.app.feature
application.client.app.product
application.client.app.releng
application.client.app.service - contains all REST web service calls
application.client.app.ui - contains all FXML files, Controller, Handler and Part Class

When running the product.product. the application works fine, but when the releng pom.xml is built and build.xml is run with fx:application toolkit="fx" and fx:deploy nativeBundles="image". EXE file is generated but when run, the fxml that should be loaded as part of "part" class is not being rendered.

Below is a sample code for a part class
`public class SearchPart {

	@PostConstruct
	public void postConstruct(BorderPane parent,@LocalInstance FXMLLoader loader) {
		try {
			loader.setLocation(getClass().getResource("../fxml/Search.fxml"));
			parent.setCenter(loader.load());
			parent.setPrefWidth(800);
			parent.setPrefHeight(50);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

}`

**feature.xml** contains application.client.app, application.client.app.service and application.client.app.ui

**product launching** configuration for VM Arguments defined as -Dorg.osgi.framework.bundle.parent=ext -Dosgi.framework.extensions=org.eclipse.fx.osgi

Any help or guidance will be much appreciated. Apologies if there are something I missed as Im new on efxclipse/rcp

**Comment by tomsontom** [comment]
This is a general java thing and not a bug in efxclipse! Relative URLs with ".." are not supported inside JAR-Filesystem. As long as you don't export you are still on the OS-Filesystem so it works there.  You need getClass().getClassloader().getResource() to make it work in the IDE and when exported
