### ISSUE TITLE
Target platform fails to resolve

### ISSUE THREAD

**Issue by vogella** [eclipse-efx/efxclipse-eclipse#47]
The instructions from https://wiki.eclipse.org/Efxclipse/Tutorials/AddingE(fx)clipse_to_eclipse fail to create a working target platform.

I assume we should use http://download.eclipse.org/efxclipse/runtime-released/3.4.0/site or http://download.eclipse.org/efxclipse/runtime-released/3.4.1/site instead of  http://download.eclipse.org/efxclipse/runtime-released/2.0.0/site as the wiki describes but the error remains the same.

Error message: https://ibb.co/f6J1Xq

**Comment by vogella** [comment]
Screenshot for http://download.eclipse.org/efxclipse/runtime-released/3.4.1/site

https://ibb.co/m6vLQA

**Comment by tomsontom** [comment]
the errors you show indicate that you forgot to UNCHECK "Include Required Software"

**Comment by vogella** [comment]
Thanks, @tomsontom, this did indeed resolve the target platform correctly.
