### ISSUE TITLE
Generated project does not compile via Maven on Java 11

### ISSUE THREAD

**Issue by vogella** [eclipse-efx/efxclipse-eclipse#50]
I use the "e4 application projects" wizard to generate an e4 Fx RCP project with "Tycho Build Stubs".

As I use Java 11 I need to update the pom file to use Tycho 1.3.0-SNAPSHOT but, as expected, the build fails due to the missing JavaFX libraries.
````
 ------------------------------------------------------------------------
[INFO] Reactor Summary for Test - releng 1.0.0-SNAPSHOT:
[INFO]
[INFO] Test - releng ...................................... SUCCESS [  0.096 s]
[INFO] Test - application bundle .......................... FAILURE [  1.597 s]
[INFO] Test - application feature ......................... SKIPPED
[INFO] Test - application product ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.585 s
[INFO] Finished at: 2018-11-19T13:24:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.3.0-SNAPSHOT:compile (default-compile) on project java11.app: Compilation failure: Compilation failure:
[ERROR] C:\Users\ex0227\workspace\efxclipse\java11.app\src\java11\app\themes\DefaultTheme.java:[1]
[ERROR]         package java11.app.themes;
[ERROR]         ^
[ERROR] The type javafx.collections.ObservableList cannot be resolved. It is indirectly referenced from required .class files
[ERROR] C:\Users\ex0227\workspace\efxclipse\java11.app\src\java11\app\themes\DefaultTheme.java:[5]
[ERROR]         public class DefaultTheme extends AbstractTheme {
[ERROR]                                           ^^^^^^^^^^^^^
[ERROR] The type javafx.collections.ListChangeListener$Change cannot be resolved. It is indirectly referenced from required .class files
[ERROR] 2 problems (2 errors)
[ERROR] -> [Help 1]
````

Could the example updated to also work on Java 11?

Where can we find the documentation how to build e4 RCP FX applications on Java 11? I have seen some blog posts that this is now supported but can't find a working example. Also GEF currently fails to compile on Java 11 for me. See https://github.com/eclipse/gef/issues/37

**Comment by tomsontom** [comment]
Right Java-11 does not have OpenJFX with it so. 

You need to add that manually to the build and later at runtime. You should have got compile errors as well in your workspace because no JavaFX classes are found - we are currently investigating if it is possible to ship JavaFX-Binaries from Eclipse.org-Servers.

**Comment by tomsontom** [comment]
A detail makeing it more complex is that one can't simply repackage the JavaFX-Binaries because they need to be run as Java-Modules.

**Comment by tomsontom** [comment]
BTW does one really need 1.3.0-SNAPSHOT? I thought 1.2.0 is enough not?

**Comment by vogella** [comment]
>           BTW does one really need 1.3.0-SNAPSHOT? I thought 1.2.0 is enough not?
AFAIK 1.3.0 is required but I'm not 100% sure. I know platform build is moving to Tycho 1.3.0 for the Java 11 build verification.

> You need to add that manually to the build and later at runtime.

Is this describes somewhere or an example available?

**Comment by tomsontom** [comment]
ok yes one needs 1.3.0 but where are those snapshots

**Comment by tomsontom** [comment]
See https://github.com/eclipse-efx/efxclipse-eclipse/wiki/Eclipse4-application-on-OpenJFX-11 once the new nighly is available

**Comment by vogella** [comment]
Thanks, Tom. What is the update site for latest e(fx)clipse 3.5.0 tooling? So far, I'm using the version included in 2018-12 but that contains "only" 3.4.1. And 3.4.1 seems to have no preference page to"point it to the lib-Folder of the OpenJFX-SDK"

**Comment by tomsontom** [comment]
http://download.eclipse.org/efxclipse/updates-nightly/site

**Comment by vogella** [comment]
http://download.eclipse.org/efxclipse/updates-nightly/site still lists 3.4.1 as version. I assume you need to update version to 3.5.0.

**Comment by tomsontom** [comment]
right would you mind fileing an issue to get that fixed

**Comment by vogella** [comment]
Also the currently nightly fails to install:

eclipse.buildId=4.10.0.I20181118-1800
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.equinox.p2.engine
Error
Tue Nov 20 09:31:25 CET 2018
An error occurred while collecting items to be installed
No repository found containing: org.eclipse.update.feature,org.eclipse.fx.runtime.min.feature,3.5.0.201811190600

and more.

**Comment by tomsontom** [comment]
was this comment meant for #51 ?

**Comment by vogella** [comment]
> was this comment meant for #51 ?

Not sure there you want get such info. #51 is about the version range, this one felt more fitting for me.

**Comment by tomsontom** [comment]
so the error message is from the maven-tycho build?

**Comment by vogella** [comment]
No, I get the message trying to install the latest tooling into the Eclipse IDE using http://download.eclipse.org/efxclipse/updates-nightly/site
