### ISSUE TITLE
http://download.eclipse.org/efxclipse/updates-nightly/site should offer 3.5.0 and not 3.4.1

### ISSUE THREAD

**Issue by vogella** [eclipse-efx/efxclipse-eclipse#51]
As noted in #50 the nightly update site offers 3.4.1. while (at this moment) it should be 3.5.0. Either the build is wrong or the version numbers are wrong.

Please fix.

**Comment by vogella** [comment]
Currently http://download.eclipse.org/efxclipse/updates-nightly/site  fails to install.

eclipse.buildId=4.10.0.I20181118-1800
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.equinox.p2.artifact.repository
Error
Tue Nov 20 09:57:45 CET 2018
No repository found containing: org.eclipse.update.feature,org.eclipse.fx.runtime.min.feature,3.5.0.201811190600

**Comment by tomsontom** [comment]
so a new version has been pushed and I could successfully install it in my eclipse 2018-09 install

**Comment by vogella** [comment]
Does not work for 2019-12. See below for the error: I'm using:

Eclipse SDK
Version: 2018-12 (4.10)
Build id: I20181119-2315
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 11.0.1

Error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: e(fx)clipse - IDE 3.5.0.201811200943 (org.eclipse.fx.ide.feature.feature.group 3.5.0.201811200943)
  Missing requirement: Core (=none UI) components 3.5.0.201811200856 (org.eclipse.fx.core 3.5.0.201811200856) requires 'osgi.bundle; com.google.guava 21.0.0' but it could not be found
  Cannot satisfy dependency:
    From: e(fx)clipse - IDE - Basic 3.5.0.201811200943 (org.eclipse.fx.ide.basic.feature.feature.group 3.5.0.201811200943)
    To: org.eclipse.equinox.p2.iu; org.eclipse.fx.core [3.5.0.201811200856,3.5.0.201811200856]
  Cannot satisfy dependency:
    From: e(fx)clipse - IDE 3.5.0.201811200943 (org.eclipse.fx.ide.feature.feature.group 3.5.0.201811200943)
    To: org.eclipse.equinox.p2.iu; org.eclipse.fx.ide.basic.feature.feature.group [3.5.0.201811200943,3.5.0.201811200943]

**Comment by tomsontom** [comment]
wonderful good old guava again - i really lean towards copying that as a private library to the project - we anyways don't show it in the API and it caused us troubles in other e4 applications already.

**Comment by tomsontom** [comment]
works flawlessly for me:
* Downloaded latest nightly of SDK
* Added updatesite
* selected first entry in update-manager - e(fx)clipse install
* made sure "Contact all update sites during install to find required software"

e(fx)clipse does not ship Guava itself but relies on fact that it is found in the sim-rel repo

**Comment by vogella** [comment]
Thanks @tomsontom, I can confirm that it works now. Maybe the http://download.eclipse.org/releases/2018-12 had a small hickup. Now, I can continue to test your new Java 11 installation instructions.

Thanks.
