### ISSUE TITLE
Migrate the SWT E4 Spy Tools to JavaFX

### ISSUE THREAD

**Issue by lauritziu** [eclipse-efx/efxclipse-eclipse#57]
To support the development of a E4 application some  very useful tools exist helping to investigate the current state of a running E4 application. To get an impression of the tools see the following [video](https://www.youtube.com/watch?v=CcClGXmZPcI).

The following tools exists:

- Model Spy (investigate the current application model)
- Context Spy (provides a deep insight into the context hierarchy with search support)
- Preferences Spy (shows available preferences and changes to it)
- Event Spy (observes all the Eclipse events fired and allows to filter the events)

These tools are great but they are all written in SWT and therefore not easily usable in a JavaFx Eclipse application.

It would be great to migrate the tools to JavaFX and provide them with the efxclipse tooling.

**Comment by lauritziu** [comment]
We have already migrated the following tools:

- Context Spy
- Preferences Spy
- Event Spy

We would like to contribute the three. This issue is mainly to document that these tools are already available and duplicate work can be avoided.

We would need to change the package names to at.bestsolution but then we can create an pullrequest. @tomsontom any further requirements that would it be easier to accept the pullrequest?

**Comment by tomsontom** [comment]
They should go to the efxclipse-rt and the package is org.eclipse.fx!

**Comment by lauritziu** [comment]
Ok and in which structure? _bundles/runtime_ would not be a good place. There are already "_demos_" and I would suggest to place it into "_tools_". They are runtime tools. The right location to know would be good to make the pullrequest easier to accept :)

**Comment by tomsontom** [comment]
Open a ticket over there and i‘ll comment there :-)

**Comment by lauritziu** [comment]
Ok, issue is created at efxclipse-rt. I'm looking forward to comments ;)
