### ISSUE TITLE
Get latest svg2fxml

### ISSUE THREAD

**Issue by piegamesde** [eclipse-efx/efxclipse-eclipse#70]
How do I get/compile the latest `svg2fxml`? An executable jar file will work for me, but a library I can get through Maven will do as well.

**Comment by tomsontom** [comment]
we are not building that since a long timeframe but the sources are still available in our rt-repo - https://github.com/eclipse-efx/efxclipse-rt/tree/3.x/modules/core/org.eclipse.fx.formats.svg

**Comment by tomsontom** [comment]
i guess the right thing to do is to make that a maven plugin but this needs to be discussed in https://github.com/eclipse-efx/efxclipse-rt
