### ISSUE TITLE
Where to download the plugin?

### ISSUE THREAD

**Issue by piegamesde** [eclipse-efx/efxclipse-eclipse#79]
On the web site, I can only find downloads for the all-in-one solution. There are [installation instructions](https://www.eclipse.org/efxclipse/install.html#for-the-ambitious) for the plugin, but there are no download links.

**Comment by Dreanaught** [comment]
There is an updated site mentioned in this post https://www.eclipse.org/forums/index.php?t=msg&th=1103134&goto=1823903&#msg_1823903
Its location is  http://download.eclipse.org/efxclipse/updates-released/3.6.0/site/

**Comment by martinbluehweis** [comment]
to install software in eclipse please follow the instructions [here](https://help.eclipse.org/2020-09/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-124.htm)

the latest version's update site is http://download.eclipse.org/efxclipse/updates-released/3.7.0/site/
