### ISSUE TITLE
Dependency failure while installing Target Platform Feature 3.7.0.202008250600

### ISSUE THREAD

**Issue by nuravgrag** [eclipse-efx/efxclipse-eclipse#80]
Hmm so i tried installing it on Eclipse 2020-06 and I followed this blog: https://tomsondev.bestsolution.at/2020/01/28/setting-up-efxclipse-rcp-development-for-java11-and-pde/. When i try to install the Target Platform Feature I am thrown the following dependency problem:

> Cannot complete the install because of a conflicting dependency.
Software being installed: e(fx)clipse - Target Platform Feature 3.7.0.202008250600 (org.eclipse.fx.target.feature.feature.group 3.7.0.202008250600)
Software currently installed: Eclipse Platform 4.16.0.v20200604-0951 (org.eclipse.platform.feature.group 4.16.0.v20200604-0951)
Only one of the following can be installed at once:
Equinox Java Authentication and Authorization Service (JAAS) 1.3.400.v20191008-0645 (org.eclipse.equinox.security 1.3.400.v20191008-0645)
Equinox Java Authentication and Authorization Service (JAAS) 1.3.500.v20200114-1637 (org.eclipse.equinox.security 1.3.500.v20200114-1637)
Equinox Java Authentication and Authorization Service (JAAS) 1.2.300.v20170505-1235 (org.eclipse.equinox.security 1.2.300.v20170505-1235)
Cannot satisfy dependency:
From: e(fx)clipse - Target Platform Feature 3.7.0.202008250600 (org.eclipse.fx.target.feature.feature.group 3.7.0.202008250600)
To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.security [1.3.400.v20191008-0645,1.3.400.v20191008-0645]
Cannot satisfy dependency:
From: Eclipse Platform 4.16.0.v20200604-0951 (org.eclipse.platform.feature.group 4.16.0.v20200604-0951)
To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.security [1.3.500.v20200114-1637,1.3.500.v20200114-1637]

Any idea how I can resolve this? I am using the nightly-site.

**Comment by tomsontom** [comment]
You never install the target Platform so i don't fully get what you are trying to tell us

**Comment by nuravgrag** [comment]
When I try to install the target platform from About -> Install Software and then from the runtime site, Eclipse says that it cannot install cause of a dependency issue. Did I miss a step by chance? I'm new at this so might have done something wrong.

**Comment by tomsontom** [comment]
I repeat - you never install a target platform you configure one.

**Comment by nuravgrag** [comment]
Ohh i see what I was saying wrong now. So when i am attempting to configure the target platform, I get stuck when I am trying to download and install the "e(fx)clipse -Target Platform Feature" as in the image below - 

<img width="1112" alt="pic1" src="https://user-images.githubusercontent.com/22535728/91237627-b8859580-e700-11ea-8422-5f9eba59b0c8.png">

Once I hit next in the above image, Eclipse throws dependency issues as I mention in my first comment. I hope this makes more sense.

**Comment by tomsontom** [comment]
I repeat you don't install the target platform. You configure that in the PDE-preferences

**Comment by nuravgrag** [comment]
Alright I finally got it and it works. Thanks for taking the time to help me understand this.

**Comment by nuravgrag** [comment]
Not an issue. Installed instead of configuring the target platform which is why the error was being thrown.
