### ISSUE TITLE
Adapt src.zip lookup to match new SDK layout

### ISSUE THREAD

**Issue by tomsontom** [eclipse-efx/efxclipse-eclipse#85]
We currently expect the src.zip to be found next to the jar files (https://github.com/eclipse-efx/efxclipse-eclipse/blob/06bad832d2584dc54b7aee6950d9d3ae725fbe9c/bundles/tooling/org.eclipse.fx.ide.jdt.core/src/org/eclipse/fx/ide/jdt/core/internal/BuildPathSupport.java#L80) - there's a plan to move the location of src.zip (https://bugs.openjdk.java.net/browse/JDK-8258499)

**Comment by spp4keba** [comment]
We face the problem that the src.zip is still set to ${JAVAFX_SDK}/lib/src.zip - can it be that the fix must also be applied to BuildPathSupport.java you mentioned? See: https://github.com/eclipse-efx/efxclipse-eclipse/blob/06bad832d2584dc54b7aee6950d9d3ae725fbe9c/bundles/tooling/org.eclipse.fx.ide.jdt.core/src/org/eclipse/fx/ide/jdt/core/internal/BuildPathSupport.java#L81 
Which would be the src.zip found in the lib folder again.
