### ISSUE TITLE
openjfx-11 p2 update site unreachable

### ISSUE THREAD

**Issue by aumann** [eclipse-efx/efxclipse-eclipse#96]
I just wanted to let you know that http://downloads.efxclipse.bestsolution.at/p2-repos/openjfx-11/repository/ is offline

**Comment by daudo** [comment]
thanks for bringing this to our attention. The issue should now be resolved.

**Comment by aumann** [comment]
thank you!

**Comment by aumann** [comment]
(Reusing this issue, hope that's ok). There seems to be a problem with an expired SSL certficate now

**Comment by daudo** [comment]
Thanks for raising the issue, we're looking into it.

**Comment by daudo** [comment]
the problem should now be resolved.

**Comment by aumann** [comment]
thank you for the quick response, lgtm!
